name: gomuks
adopt-info: gomuks
summary: A TUI for Matrix.
description: |
  A terminal Matrix client written in Go using mautrix and mauview.
  https://maunium.net/go/gomuks/

base: core22
icon: icon.png
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

build-snaps:
  - go

apps:
  gomuks:
    command: bin/gomuks
    plugs:
      - network

parts:
  gomuks:
    plugin: go
    source: https://github.com/tulir/gomuks.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - libolm-dev
    stage-packages:
      - libolm3
