name: gomuks
adopt-info: gomuks
license:  AGPL-3.0
summary: A TUI for Matrix.
description: |
  A terminal Matrix client written in Go using mautrix and mauview.

base: core22
icon: icon.png
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

build-snaps:
  - go

apps:
  gomuks:
    command: bin/gomuks
    plugs:
      - desktop
      - home
      - network
      - network-bind

parts:
  gomuks:
    plugin: go
    source: https://github.com/tulir/gomuks.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - libolm-dev
    stage-packages:
      - libolm3
